services:
  ethereum:
    platform: linux/amd64
    image: ghcr.io/breadchaincoop/ethereum:dev
    env_file:
      - .env
    ports:
      - "8545:8545"
  
  eigenlayer:
    platform: linux/amd64
    image: ghcr.io/breadchaincoop/eigenlayer:dev
    depends_on:
      - ethereum
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes
      - ./config/config.json:/bls-middleware/contracts/docker/eigenlayer/config.json
    command: sh -c "mkdir -p /root/.nodes/operator_keys && /main.sh"
  
  signer:
    image: ghcr.io/layr-labs/cerberus:0.0.2
    platform: linux/amd64
    ports:
      - "${CERBERUS_METRICS_PORT:-9081}:${CERBERUS_METRICS_PORT:-9081}"
      - "${CERBERUS_GRPC_PORT:-50051}:${CERBERUS_GRPC_PORT:-50051}"
    environment:
      - "METRICS_PORT=${CERBERUS_METRICS_PORT:-9081}"
    env_file:
      - .env
    restart: unless-stopped

  # Wait for eigenlayer to complete setup
  wait-for-setup:
    image: busybox
    depends_on:
      - eigenlayer
    command: sh -c "sleep 60 && echo 'Setup should be complete'"

  # AVS Node Contributors
  node1:
    image: ghcr.io/breadchaincoop/commonware-avs-node:latest
    platform: linux/amd64
    depends_on:
      - wait-for-setup
      - signer
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes:ro
      - ./config/orchestrator.json:/root/orchestrator.json:ro
    ports:
      - "3001:3001"
    command: ["--key-file", "/root/.nodes/operator_keys/testacc1.private.bls.key.json", "--port", "3001", "--orchestrator", "/root/orchestrator.json"]
    restart: unless-stopped

  node2:
    image: ghcr.io/breadchaincoop/commonware-avs-node:latest
    platform: linux/amd64
    depends_on:
      - wait-for-setup
      - signer
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes:ro
      - ./config/orchestrator.json:/root/orchestrator.json:ro
    ports:
      - "3002:3002"
    command: ["--key-file", "/root/.nodes/operator_keys/testacc2.private.bls.key.json", "--port", "3002", "--orchestrator", "/root/orchestrator.json"]
    restart: unless-stopped

  node3:
    image: ghcr.io/breadchaincoop/commonware-avs-node:latest
    platform: linux/amd64
    depends_on:
      - wait-for-setup
      - signer
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes:ro
      - ./config/orchestrator.json:/root/orchestrator.json:ro
    ports:
      - "3003:3003"
    command: ["--key-file", "/root/.nodes/operator_keys/testacc3.private.bls.key.json", "--port", "3003", "--orchestrator", "/root/orchestrator.json"]
    restart: unless-stopped

  # AVS Router
  router:
    image: ghcr.io/breadchaincoop/commonware-avs-router:latest
    platform: linux/amd64
    depends_on:
      - node1
      - node2
      - node3
    env_file:
      - .env
    environment:
      - INGRESS=true
    volumes:
      - ./.nodes:/root/.nodes:ro
      - ./config/orchestrator.json:/root/orchestrator.json:ro
    ports:
      - "8080:8080"
    restart: unless-stopped