services:
  ethereum:
    platform: linux/amd64
    image: ghcr.io/breadchaincoop/ethereum:dev
    env_file:
      - .env
    ports:
      - "8545:8545"
  
  eigenlayer:
    platform: linux/amd64
    image: ghcr.io/breadchaincoop/eigenlayer:dev
    depends_on:
      - ethereum
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes
      - ./config/config.json:/bls-middleware/contracts/docker/eigenlayer/config.json
  
  signer:
    image: ghcr.io/layr-labs/cerberus:0.0.2
    platform: linux/amd64
    ports:
      - "${CERBERUS_METRICS_PORT:-9081}:${CERBERUS_METRICS_PORT:-9081}"
      - "${CERBERUS_GRPC_PORT:-50051}:${CERBERUS_GRPC_PORT:-50051}"
    environment:
      - "METRICS_PORT=${CERBERUS_METRICS_PORT:-9081}"
    env_file:
      - .env
    restart: unless-stopped