services:
  ethereum:
    platform: linux/amd64
    build:
      context: ./docker/ethereum
      dockerfile: Dockerfile.ethereum
    env_file:
      - .env
    ports:
      - "8545:8545"
  
  eigenlayer:
    platform: linux/amd64
    build:
      context: ./docker/eigenlayer
      dockerfile: Dockerfile.eigenlayer
    depends_on:
      - ethereum
    env_file:
      - .env
    volumes:
      - ./.nodes:/root/.nodes
      - ./docker/eigenlayer/config.json:/bls-middleware/contracts/docker/eigenlayer/config.json
  
  signer:
    image: ghcr.io/layr-labs/cerberus:0.0.2
    platform: linux/amd64
    ports:
      - "${CERBERUS_METRICS_PORT}:${CERBERUS_METRICS_PORT}"
      - "${CERBERUS_GRPC_PORT}:${CERBERUS_GRPC_PORT}"
    environment:
      - "METRICS_PORT=${CERBERUS_METRICS_PORT}"
    env_file:
      - .env
    restart: unless-stopped
