[package]
name = "avs-scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "verify_increments"
path = "verify_increments.rs"

[dependencies]
alloy = { version = "0.12.6" }
tokio = { version = "1.0", features = ["full"] }
commonware-eigenlayer = { git = "https://github.com/BreadchainCoop/commonware-avs-network-lookup" }
url = "2.5.4"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
commonware-avs-router = { path = ".." } 